const RESPONSE_MESSAGE = {
    SIGNUP_SUCCESS: "Registered successfully",
    LOGIN_SUCCESS: "Login successfully",
    LOGIN_FAILED: "Failed to login",
    SIGNUP_FAILED: "Failed to signup",
    EMAIL_EXIST: "Email Already Exist",
    EMAIL_DOESNT_EXIST: "Email Doesn't Exists",
    INVALID_CREDENTIAL: "Invalid Credential",
    INVALID_USER: "Invalid User",
    BLOCK_ACCOUNT: "Account has been blocked for next 5 minutes",
    UNAUTHORIZED: "Authentication required",
    TOKEN_EXPIRE: "Login Again",
    USER_NOT_FOUND: "User not found",
    RESTAURANT_NOT_FOUND: "Restaurant not found",
    RIDER_NOT_FOUND: "No Rider Found",
    CART_CREATED: "Cart Created Successfully",
    CART_NOT_FOUND: "Cart Not Found",
    CART_ALREADY_EXISTS: "Cart already exits",
    CART_RESTAURANT_ERROR: "Order from the same restaurant or delete previous ",
    INVALID_CART: "Cart is not valid to create order",
    INVALID_REQUEST: "Request is not valid",
    INVALID_DATA: "Please provide valid data",
    INVALID_FILTER_OPTION: "Filter option is not valid",
    INVALID_SORTING_OPTION: "Sorting option is not valid",
    NO_RESTAURANT_FOUND: "No Restaurants Found",
    DELETE_CART: "Cart Deleted Successfully",
    FAILED_CREATE_ORDER: "Failed to create order",
    ORDER_NOT_FOUND: "Order not found",
    ORDER_PROCESSING: "Order is Processing",
    ORDER_READY: "Order is Ready",
    ORDER_REACHED: "Rider has reached the destination",
    FAILED_TO_PROCESS: "Failed to Process",
    TRANSACTION_COMPLETE: "Complete Transaction"
};

module.exports = RESPONSE_MESSAGE;